name: qr_code_scanner
description: Fork of QR code scanner that can be embedded inside flutter. It uses zxing in Android and MTBBarcode scanner in iOS.
version: 0.0.13
author: doldremus
homepage: https://bitstage.by
repository: https://github.com/doldremus/qr_code_scanner

environment:
  sdk: ">=2.3.0 <3.0.0"
  flutter: ^1.10.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.9.0

flutter:
  plugin:
    platforms:
      android:
        package: net.touchcapture.qr.flutterqr
        pluginClass: FlutterQrPlugin
      ios:
        pluginClass: FlutterQrPlugin
